#!/bin/bash
# claude-review — Review a GitHub PR via CLI (Zero API keys required!)
# Usage: bash pr-review.sh --pr https://github.com/owner/repo/pull/123
#        bash pr-review.sh --pr 123 --repo owner/repo

set -euo pipefail

while [[ $# -gt 0 ]]; do
  case "$1" in
    --pr) PR_REF="$2"; shift 2 ;;
    --repo) REPO="$2"; shift 2 ;;
    --output) OUTPUT="$2"; shift 2 ;;
    *) echo "Usage: $0 --pr <url|number> [--repo owner/repo] [--output file.md]"; exit 1 ;;
  esac
done

if echo "$PR_REF" | grep -qE '^https?://'; then
  REPO=$(echo "$PR_REF" | sed -E 's|https?://github.com/||' | sed -E 's|/pull/[0-9]+.*||')
  PR_NUM=$(echo "$PR_REF" | sed -E 's|.*/pull/||' | sed -E 's|/.*||')
elif echo "$PR_REF" | grep -qE '^[0-9]+$'; then
  PR_NUM="$PR_REF"
fi

if [ -z "${REPO:-}" ] || [ -z "${PR_NUM:-}" ]; then
  echo "Usage: $0 --pr https://github.com/owner/repo/pull/123"
  exit 1
fi

OUTPUT="${OUTPUT:-pr_review_${PR_NUM}.md}"
echo "Reviewing PR #$PR_NUM on $REPO"

# Fetch PR data (no token needed for public repos)
PR_DATA=$(curl -s "https://api.github.com/repos/$REPO/pulls/$PR_NUM")
PR_DIFF=$(curl -s -H "Accept: application/vnd.github.v3.diff" \
  "https://api.github.com/repos/$REPO/pulls/$PR_NUM")

PR_TITLE=$(echo "$PR_DATA" | grep '"title"' | head -1 | sed 's/.*"title": "\(.*\)",/\1/')
PR_BODY=$(echo "$PR_DATA" | grep '"body"' | head -1 | sed 's/.*"body": "\(.*\)",/\1/')
CHANGED=$(echo "$PR_DATA" | grep '"changed_files"' | sed 's/.*: //;s/,//')
ADDITIONS=$(echo "$PR_DATA" | grep '"additions"' | sed 's/.*: //;s/,//')
DELETIONS=$(echo "$PR_DATA" | grep '"deletions"' | sed 's/.*: //;s/,//')

echo "PR: $PR_TITLE"
echo "Files: $CHANGED | +$ADDITIONS/-$DELETIONS"

# Heuristic analysis (works without any API key)
LINES=$(echo "$PR_DIFF" | wc -l)
FILES_CHANGED=$(echo "$PR_DIFF" | grep '^diff --git' | wc -l)
NEW_FILES=$(echo "$PR_DIFF" | grep '^new file' | wc -l)
DEL_FILES=$(echo "$PR_DIFF" | grep '^deleted file' | wc -l)
COMMENTS_IN_CODE=$(echo "$PR_DIFF" | grep -c '^+.*//\|^+.*#\|^+.*<!--\|^+.*/\\*' || true)
TEST_CHANGES=$(echo "$PR_DIFF" | grep -c 'test\|spec\|__test__' || true)
SECURITY_KEYWORDS=$(echo "$PR_DIFF" | grep -ci 'password\|token\|secret\|key\|api_key\|credential' || true)
CONSOLE_LOGS=$(echo "$PR_DIFF" | grep -c 'console.log\|console.error\|print(' || true)

# Generate risks
RISKS=""
if [ "$SECURITY_KEYWORDS" -gt 0 ]; then RISKS="$RISKS\n- Security: Potential credential exposure detected"; fi
if [ "$CONSOLE_LOGS" -gt 0 ]; then RISKS="$RISKS\n- Debug: Console.log/print statements left in code"; fi
if [ "$LINES" -gt 500 ]; then RISKS="$RISKS\n- Size: Large diff ($LINES lines) — harder to review thoroughly"; fi
if [ "$NEW_FILES" -gt 5 ]; then RISKS="$RISKS\n- Scope: $NEW_FILES new files added — check for unnecessary additions"; fi
if [ -z "$RISKS" ]; then RISKS="No significant risks detected."; fi

# Generate suggestions
SUGGESTIONS=""
if [ "$COMMENTS_IN_CODE" -lt 3 ] && [ "$LINES" -gt 100 ]; then
  SUGGESTIONS="$SUGGESTIONS\n- Add inline comments for complex logic"
fi
if [ "$TEST_CHANGES" -eq 0 ] && [ "$LINES" -gt 50 ]; then
  SUGGESTIONS="$SUGGESTIONS\n- Include test coverage for new/changed functionality"
fi
SUGGESTIONS="$SUGGESTIONS\n- Consider adding a brief summary in the PR description if missing"

# Confidence score
if [ "$LINES" -lt 100 ]; then SCORE="High — Small, focused change"
elif [ "$LINES" -lt 500 ]; then SCORE="Medium — Moderate size, manual spot-check recommended"
else SCORE="Low — Large diff, thorough manual review recommended"
fi

cat > "$OUTPUT" << REVIEWEOF
# PR Review: #$PR_NUM — $PR_TITLE

**Repository:** $REPO  
**Files Changed:** $CHANGED (+$ADDITIONS/-$DELETIONS)  
**Analysis Method:** Static heuristic analysis (no API keys required)  

---

## Summary
$([[ -n "$PR_BODY" ]] && echo "$PR_BODY" || echo "This PR modifies $FILES_CHANGED file(s) across $CHANGED changed files.")

## Identified Risks
$RISKS

## Improvement Suggestions
$SUGGESTIONS

## Confidence Score
$SCORE

---

_Generated by [claude-review](https://github.com/Freeman88-tch) on $(date +%Y-%m-%d) — Zero API keys required_
REVIEWEOF

echo "Review saved: $OUTPUT"
head -5 "$OUTPUT"
