#!/usr/bin/env python3
"""claude-review: 自动PR审查Agent"""

import subprocess, json, sys, os, re

def fetch_pr_diff(pr_url):
    """从GitHub拉PR diff"""
    # 解析owner/repo/pr_number
    m = re.search(r'github\.com/([^/]+)/([^/]+)/pull/(\d+)', pr_url)
    if not m:
        sys.exit("❌ 无效的PR URL")
    owner, repo, pr_num = m.group(1), m.group(2), m.group(3)
    
    # 用gh CLI
    cmd = f"gh pr view {pr_num} --repo {owner}/{repo} --json body,title,additions,deletions,files,headRefName,baseRefName"
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    info = json.loads(result.stdout)
    
    # 拉diff
    diff_cmd = f"gh pr diff {pr_num} --repo {owner}/{repo}"
    diff_result = subprocess.run(diff_cmd, shell=True, capture_output=True, text=True)
    
    return info, diff_result.stdout

def analyze_diff(diff_text, pr_info):
    """分析PR diff"""
    lines = diff_text.split('\n')
    files_changed = []
    current_file = ""
    added_lines = []
    removed_lines = []
    
    for line in lines:
        if line.startswith('diff --git'):
            if current_file:
                files_changed.append({
                    'file': current_file,
                    'additions': len(added_lines),
                    'deletions': len(removed_lines)
                })
                added_lines = []
                removed_lines = []
            current_file = line.split(' b/')[-1] if ' b/' in line else ""
        elif line.startswith('+') and not line.startswith('+++'):
            added_lines.append(line[1:])
        elif line.startswith('-') and not line.startswith('---'):
            removed_lines.append(line[1:])
    
    if current_file:
        files_changed.append({
            'file': current_file,
            'additions': len(added_lines),
            'deletions': len(removed_lines)
        })
    
    # 找潜在风险
    risks = []
    improvements = []
    
    risk_patterns = [
        (r'(api_key|password|secret|token|credential)\s*=', "⚠️ 硬编码凭据风险"),
        (r'print\(|console\.log\(', "🔧 调试输出残留"),
        (r'(eval|exec|subprocess\.call)\s*\(', "🔓 代码注入风险"),
        (r'try\s*:\s*\n\s*pass\s*\n\s*(except|finally)', "⚠️ 空白异常处理"),
        (r'import\s+\*\s*$', "⚠️ 通配符导入"),
        (r'DELETE|DROP\s+TABLE|rm\s+-rf', "⚠️ 危险操作调用"),
        (r'(#\s*TODO|//\s*TODO|<!--\s*TODO)', "📝 遗留待办"),
        (r'.{120,}', "⚠️ 超长行（>120字符）"),
    ]
    
    for i, line in enumerate(lines):
        for pattern, risk_msg in risk_patterns:
            if re.search(pattern, line):
                risks.append(f"{risk_msg}: {current_file}:{i+1}")
    
    # 改进建议
    if files_changed:
        total_additions = sum(f['additions'] for f in files_changed)
        if len(files_changed) > 10:
            improvements.append("💡 PR改动文件过多（{}个），建议拆分为小PR".format(len(files_changed)))
        if total_additions > 500:
            improvements.append("💡 单PR改动量过大（+{}行），建议拆分".format(total_additions))
    
    return {
        'files_changed': files_changed,
        'total_additions': pr_info.get('additions', len(added_lines)),
        'total_deletions': pr_info.get('deletions', len(removed_lines)),
        'risks': risks[:10],
        'improvements': improvements
    }

def generate_review(analysis, pr_info):
    """生成结构化Markdown审查报告"""
    title = pr_info.get('title', '')
    body_summary = pr_info.get('body', '')[:200]
    
    report = f"""## 🤖 Claude Code PR Review

### 📋 改动概要
**PR**: {title}
**分支**: {pr_info.get('baseRefName','')} ← {pr_info.get('headRefName','')}
**改动**: +{analysis['total_additions']}/-{analysis['total_deletions']} 行, {len(analysis['files_changed'])} 个文件

### 变更文件
"""
    for f in analysis['files_changed']:
        report += f"- `{f['file']}` (+{f['additions']}/-{f['deletions']})\n"
    
    report += f"""
### ⚠️ 风险项
"""
    if analysis['risks']:
        for r in analysis['risks']:
            report += f"- {r}\n"
    else:
        report += "- ✅ 无显著风险\n"
    
    report += f"""
### 💡 改进建议
"""
    if analysis['improvements']:
        for i in analysis['improvements']:
            report += f"- {i}\n"
    else:
        report += "- ✅ 当前改动合理\n"
    
    # 置信度评分
    risk_count = len(analysis['risks'])
    if risk_count == 0:
        confidence = "High ✅"
    elif risk_count <= 3:
        confidence = "Medium ⚠️"
    else:
        confidence = "Low ❌"
    
    report += f"""
### 📊 置信度评分：{confidence}

---
*Generated by claude-review v1.0 | {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M')}*
"""
    return report

def main():
    if len(sys.argv) < 2:
        sys.exit("用法: python3 review.py <pr_url>")
    
    pr_url = sys.argv[1]
    gh_available = subprocess.run("which gh", shell=True, capture_output=True)
    if gh_available.returncode != 0:
        sys.exit("❌ 需要安装 GitHub CLI (gh)")
    
    print(f"🔍 分析PR: {pr_url}")
    
    try:
        pr_info, diff_text = fetch_pr_diff(pr_url)
        analysis = analyze_diff(diff_text, pr_info)
        report = generate_review(analysis, pr_info)
        print(report)
        
        # 保存为文件
        with open("review_output.md", "w") as f:
            f.write(report)
        print(f"\n📁 输出已保存: review_output.md")
        
    except Exception as e:
        print(f"❌ 分析失败: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
