#!/bin/bash
# changelog.sh — Auto-generate structured CHANGELOG.md from git history
# Usage: bash changelog.sh [--since <tag|date>] [--repo <path>]

set -euo pipefail

# Defaults
SINCE="${2:-$(git describe --tags --abbrev=0 2>/dev/null || echo 'HEAD~50')}"
REPO_DIR="${4:-.}"
OUTPUT="CHANGELOG.md"
VERBOSE=false

# Parse args
while [[ $# -gt 0 ]]; do
  case "$1" in
    --since) SINCE="$2"; shift 2 ;;
    --repo)  REPO_DIR="$2"; shift 2 ;;
    --output) OUTPUT="$2"; shift 2 ;;
    --verbose) VERBOSE=true; shift ;;
    *) shift ;;
  esac
done

cd "$REPO_DIR"

# Validate git repo
if ! git rev-parse --git-dir > /dev/null 2>&1; then
  echo "❌ Not a git repository: $REPO_DIR"
  exit 1
fi

echo "🔍 Generating changelog since: $SINCE"

# Get the last release tag for version header
LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
COMMITS=$(git log "$SINCE"..HEAD --format="%H||%s||%an||%ad" --date=short 2>/dev/null)

if [ -z "$COMMITS" ]; then
  echo "⚠️  No commits found since $SINCE"
  echo "# Changelog" > "$OUTPUT"
  echo "" >> "$OUTPUT"
  echo "No changes since $SINCE." >> "$OUTPUT"
  echo "✅ $OUTPUT generated (empty)"
  exit 0
fi

# Categorize commits
ADDED=()
FIXED=()
CHANGED=()
REMOVED=()
OTHER=()

while IFS='||' read -r HASH MESSAGE AUTHOR DATE; do
  # Normalize message to lowercase for pattern matching
  LC_MSG=$(echo "$MESSAGE" | tr '[:upper:]' '[:lower:]')
  
  if echo "$LC_MSG" | grep -qE '^(feat|add|feature|implement|introduce|new)'; then
    ADDED+=("$HASH|$MESSAGE|$AUTHOR|$DATE")
  elif echo "$LC_MSG" | grep -qE '^(fix|bug|hotfix|patch|correct|resolve)'; then
    FIXED+=("$HASH|$MESSAGE|$AUTHOR|$DATE")
  elif echo "$LC_MSG" | grep -qE '^(chore|refactor|update|upgrade|bump|improve|optimize)'; then
    CHANGED+=("$HASH|$MESSAGE|$AUTHOR|$DATE")
  elif echo "$LC_MSG" | grep -qE '^(remove|delete|deprecate|drop|clean)'; then
    REMOVED+=("$HASH|$MESSAGE|$AUTHOR|$DATE")
  else
    OTHER+=("$HASH|$MESSAGE|$AUTHOR|$DATE")
  fi
done <<< "$COMMITS"

# Get current date
RELEASE_DATE=$(date +%Y-%m-%d)

# Generate CHANGELOG.md
{
  echo "# Changelog"
  echo ""
  echo "## [$LAST_TAG] - $RELEASE_DATE"
  echo ""

  if [ ${#ADDED[@]} -gt 0 ]; then
    echo "### Added"
    for entry in "${ADDED[@]}"; do
      IFS='|' read -r HASH MSG AUTHOR DATE <<< "$entry"
      echo "- **$AUTHOR**: $MSG"
    done
    echo ""
  fi

  if [ ${#FIXED[@]} -gt 0 ]; then
    echo "### Fixed"
    for entry in "${FIXED[@]}"; do
      IFS='|' read -r HASH MSG AUTHOR DATE <<< "$entry"
      echo "- **$AUTHOR**: $MSG"
    done
    echo ""
  fi

  if [ ${#CHANGED[@]} -gt 0 ]; then
    echo "### Changed"
    for entry in "${CHANGED[@]}"; do
      IFS='|' read -r HASH MSG AUTHOR DATE <<< "$entry"
      echo "- **$AUTHOR**: $MSG"
    done
    echo ""
  fi

  if [ ${#REMOVED[@]} -gt 0 ]; then
    echo "### Removed"
    for entry in "${REMOVED[@]}"; do
      IFS='|' read -r HASH MSG AUTHOR DATE <<< "$entry"
      echo "- **$AUTHOR**: $MSG"
    done
    echo ""
  fi

  if [ ${#OTHER[@]} -gt 0 ]; then
    echo "### Other"
    for entry in "${OTHER[@]}"; do
      IFS='|' read -r HASH MSG AUTHOR DATE <<< "$entry"
      echo "- **$AUTHOR**: $MSG"
    done
    echo ""
  fi

  echo "---"
  echo "_Generated by [changelog.sh](https://github.com/Freeman88-tch)_"
} > "$OUTPUT"

echo "✅ $OUTPUT generated"
echo "   ● ${#ADDED[@]} Added"
echo "   ● ${#FIXED[@]} Fixed"
echo "   ● ${#CHANGED[@]} Changed"
echo "   ● ${#REMOVED[@]} Removed"
echo "   ● ${#OTHER[@]} Other"
echo ""
echo "📄 Output: $(pwd)/$OUTPUT"
