#!/bin/bash
# changelog.sh — Auto-generate structured CHANGELOG.md from git history
# Usage: bash changelog.sh [--since <tag|date>] [--repo <path>]

set -euo pipefail

# Defaults
SINCE=""
REPO_DIR="."
OUTPUT="CHANGELOG.md"

# Parse args
while [[ $# -gt 0 ]]; do
  case "$1" in
    --since) SINCE="$2"; shift 2 ;;
    --repo)  REPO_DIR="$2"; shift 2 ;;
    --output) OUTPUT="$2"; shift 2 ;;
    *) shift ;;
  esac
done

cd "$REPO_DIR"

# Validate git repo
if ! git rev-parse --git-dir > /dev/null 2>&1; then
  echo "❌ Not a git repository: $REPO_DIR"
  exit 1
fi

# Determine since point
if [ -z "$SINCE" ]; then
  LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
  if [ -n "$LAST_TAG" ]; then
    SINCE="$LAST_TAG"
  else
    SINCE="HEAD~50"
  fi
fi

echo "🔍 Generating changelog since: $SINCE"

# Get commits as tab-separated values
COMMITS=$(git log "$SINCE"..HEAD --format="%H%x09%s%x09%an%x09%ad" --date=short 2>/dev/null || true)

if [ -z "$COMMITS" ]; then
  echo "⚠️  No commits found since $SINCE"
  {
    echo "# Changelog"
    echo ""
    echo "No changes since $SINCE."
  } > "$OUTPUT"
  echo "✅ $OUTPUT generated (empty)"
  exit 0
fi

# Categorize commits
ADDED=()
FIXED=()
CHANGED=()
REMOVED=()
OTHER=()

while IFS=$'\t' read -r HASH MESSAGE AUTHOR DATE; do
  [ -z "$HASH" ] && continue
  
  # Extract first word of commit message (lowercase)
  FIRST_WORD=$(echo "$MESSAGE" | sed 's/[^a-zA-Z].*$//' | tr '[:upper:]' '[:lower:]')
  
  case "$FIRST_WORD" in
    feat|add|feature|implement|introduce|new)
      ADDED+=("$MESSAGE|$AUTHOR|$DATE") ;;
    fix|bug|hotfix|patch|correct|resolve)
      FIXED+=("$MESSAGE|$AUTHOR|$DATE") ;;
    chore|refactor|update|upgrade|bump|improve|optimize)
      CHANGED+=("$MESSAGE|$AUTHOR|$DATE") ;;
    remove|delete|deprecate|drop|clean)
      REMOVED+=("$MESSAGE|$AUTHOR|$DATE") ;;
    *)
      OTHER+=("$MESSAGE|$AUTHOR|$DATE") ;;
  esac
done <<< "$COMMITS"

# Generate CHANGELOG.md
{
  echo "# Changelog"
  echo ""

  LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
  RELEASE_DATE=$(date +%Y-%m-%d)
  echo "## [$LAST_TAG] - $RELEASE_DATE"
  echo ""

  if [ ${#ADDED[@]} -gt 0 ]; then
    echo "### Added"
    for entry in "${ADDED[@]}"; do
      IFS='|' read -r MSG AUTHOR DATE <<< "$entry"
      echo "- **$AUTHOR**: $MSG"
    done
    echo ""
  fi

  if [ ${#FIXED[@]} -gt 0 ]; then
    echo "### Fixed"
    for entry in "${FIXED[@]}"; do
      IFS='|' read -r MSG AUTHOR DATE <<< "$entry"
      echo "- **$AUTHOR**: $MSG"
    done
    echo ""
  fi

  if [ ${#CHANGED[@]} -gt 0 ]; then
    echo "### Changed"
    for entry in "${CHANGED[@]}"; do
      IFS='|' read -r MSG AUTHOR DATE <<< "$entry"
      echo "- **$AUTHOR**: $MSG"
    done
    echo ""
  fi

  if [ ${#REMOVED[@]} -gt 0 ]; then
    echo "### Removed"
    for entry in "${REMOVED[@]}"; do
      IFS='|' read -r MSG AUTHOR DATE <<< "$entry"
      echo "- **$AUTHOR**: $MSG"
    done
    echo ""
  fi

  if [ ${#OTHER[@]} -gt 0 ]; then
    echo "### Other"
    for entry in "${OTHER[@]}"; do
      IFS='|' read -r MSG AUTHOR DATE <<< "$entry"
      echo "- **$AUTHOR**: $MSG"
    done
    echo ""
  fi

  echo "---"
  echo "_Generated by [changelog.sh](https://github.com/Freeman88-tch)_"
} > "$OUTPUT"

echo "✅ $OUTPUT generated"
echo "   ● ${#ADDED[@]} Added"
echo "   ● ${#FIXED[@]} Fixed"
echo "   ● ${#CHANGED[@]} Changed"
echo "   ● ${#REMOVED[@]} Removed"
echo "   ● ${#OTHER[@]} Other"
echo ""
echo "📄 Output: $(pwd)/$OUTPUT"
